### ISSUE TITLE
SSH Option doesn't have a ryu-shim button.

### ISSUE THREAD

**Issue by GonzaloFajardoMedina** [fp7-netide/IDE#19]
Hi,
it is not implemented the option to choose ryu as shim , right?
![shim](https://cloud.githubusercontent.com/assets/11718117/16090058/3b915ada-332e-11e6-8c52-a7f0f959ac9a.png)

Thanks.

**Comment by ElisaRojas** [comment]
Hi again @cstritzke . Apparently @doriguzzi is also having some problems

**Comment by ElisaRojas** [comment]
Sorry, I closed it by mistake :smile: @cstritzke , could you give any feedback? Sergio told us today that you would fix this, but the thing is that we need it to continue developing the IDE part of the verificator...  Would it be possible to fix it soon? Thank you!

**Comment by cstritzke** [comment]
There's a new commit on the master branch that should hopefully fix it. Sorry for the delay - somehow the notifications were sent to me only just now...

Please let me know it it works.

**Comment by ElisaRojas** [comment]
Thank you @cstritzke ! @GonzaloFajardoMedina , please let us know if it's working now :)

**Comment by GonzaloFajardoMedina** [comment]
Now,, the ryu-shim button is available and runs without problem:
![fix_error](https://cloud.githubusercontent.com/assets/11718117/16300678/6e09a77e-3941-11e6-8e6d-d49b2f81c21f.png)

 Thanks @cstritzke !!!
