### ISSUE TITLE
Problems with ryu-backend in ssh option

### ISSUE THREAD

**Issue by GonzaloFajardoMedina** [fp7-netide/IDE#21]
Hi @cstritzke,
I run the Core, the ryu-shim and mininet without problems using the ssh option. But, ryu-backend doesn't work well.
Do you know what is the problem?
![ssh-backend](https://cloud.githubusercontent.com/assets/11718117/17060372/f29f76fe-5029-11e6-8b44-5045eee42338.png)

Thanks.

**Comment by ElisaRojas** [comment]
Hi @GonzaloFajardoMedina , I think the module is called SimpleSwitch and not simple_switch, could it be related with that?

**Comment by cstritzke** [comment]
Hi @GonzaloFajardoMedina, I need more information on the issue. Could you please post your Vagrant file, the output of the `tree` command in the apps folder and the xml-representation of the wb file?
Thanks

**Comment by GonzaloFajardoMedina** [comment]
Hi @cstritzke 
I show you that:
Vagrantfile:
![vagrantfile](https://cloud.githubusercontent.com/assets/11718117/17117790/2e2b7d4e-52be-11e6-8fa9-63054521b0ea.png)

Tree command in the app folder:
![tree](https://cloud.githubusercontent.com/assets/11718117/17117912/b8be3c80-52be-11e6-9241-1b7a57b43978.png)

And xml-representation:
https://drive.google.com/file/d/0B8Ooz7bmUcNCOXlWVUFyQjNtd2M/view?usp=sharing

Thanks for the help.

**Comment by cstritzke** [comment]
Do you only have this one simple switch app in your apps folder?

**Comment by GonzaloFajardoMedina** [comment]
Yes, sure!

**Comment by cstritzke** [comment]
And you started your machine with vagrant up? If you just started the VM, the apps folder will not be mounted.

**Comment by GonzaloFajardoMedina** [comment]
Yes, I did, Before to change the Core, it didn't happen and I could do "vagrant up" when I run the VM and it doesn't give any problem. I think not still happens.

**Comment by cstritzke** [comment]
The solution was to consistently use "vagrant up" to start the machine. Starting the test VM with VirtualBox does not mount the app folder into the machine which leads to the error.
