### ISSUE TITLE
Running a topology with one switch (some questions...)

### ISSUE THREAD

**Issue by ElisaRojas** [fp7-netide/IDE#24]
Hi,

I've reinstalled the IDE with the latest version of master and tried to test the simplest topology: one switch + two hosts... and I have several questions for @cstritzke or anyone able to do so:

1) Is it necessary to **generate the Mininet script**? I remember that was necessary before. I tried to run the VM with and without generating it and I got the same result. Could somebody clarify this?

2) When **running the NetIDE project**, I can either choose single controllers, the NetworkEngine or the Core. This is not very clear to me. Should I choose the Core or the NetworkEngine? As fas as I understand, there should be NetworkEngine (Pyretic) and NetworkEngine (NetIDE API/Core), but both should be called the same.

3)  If I run the **Core option**, I obtain the following error and two closed terminals "Core" and "Emulator". 

![oneswitchryu-core](https://cloud.githubusercontent.com/assets/2779496/17972289/8466de0a-6ade-11e6-8059-f4cb9007cf36.png)
- The "Emulator" window should not be necessary anymore, so I run the other option just in case "Core" was not the good option.

4) If I run the **NetworkEngine option**, I then get the Management GUI, but it is blank:

![oneswitchryu-networkengine](https://cloud.githubusercontent.com/assets/2779496/17972362/c9ef6bd6-6ade-11e6-92e3-1113a77a94a3.png)
- If I press "Up", it keeps the same state. If I press "Provision", it stays forever at this point and never advances:

![oneswitchryu-networkengine-provision](https://cloud.githubusercontent.com/assets/2779496/17972387/e24c145e-6ade-11e6-9b05-da90e8439a76.png)
- At the same time, all windows are closed in the terminal. If I try to open Mininet for example, I get this:

![oneswitchryu-networkengine-mininet](https://cloud.githubusercontent.com/assets/2779496/17972458/11a8e95c-6adf-11e6-98f1-465fbb19a901.png)
- If I open the workbench and hit "On" for Mininet, I get the following error.

![oneswitchryu-networkengine-mininet2](https://cloud.githubusercontent.com/assets/2779496/17972760/2946c8a8-6ae0-11e6-91f9-7b2e2102562a.png)

5) Finally, in the case I want to **use SSH**. I have another question, can I use my own VM (created manually by me) or should I always use a VM previously generated via Vagrant in the IDE?

Could somebody clarify these points to me? _**Any help would be really appreciated**_!!
Also, please @cstritzke , I think it would be nice to add all of this information to the wiki: https://github.com/fp7-netide/IDE/wiki/Usage (maybe it's too obvious, but not for me, as you can see :smile: ).

Much thanks in advance!!

**Comment by ElisaRojas** [comment]
Hi all,

Answering myself after talking with @cstritzke ...

1) Is it necessary to generate the Mininet script? I remember that was necessary before. I tried to run the VM with and without generating it and I got the same result. Could somebody clarify this?

> Still unclear, but I've done it anyway.

2) When running the NetIDE project, I can either choose single controllers, the NetworkEngine or the Core. This is not very clear to me. Should I choose the Core or the NetworkEngine? As fas as I understand, there should be NetworkEngine (Pyretic) and NetworkEngine (NetIDE API/Core), but both should be called the same.
3) + 4) (related)

> Projects are not executed anymore with `Run As...`, etc, but with the workbench menu, so questions 2, 3 and 4 do not apply anymore.
> To run the workbench, we should initialize the Vagrant file and then "vagrant up" to create the VM. If something fails or becomes unstable, we can run "vagrant destroy" (from a console) first to clean it up and start from scratch.

5) Finally, in the case I want to use SSH. I have another question, can I use my own VM (created manually by me) or should I always use a VM previously generated via Vagrant in the IDE?

> We can use any VM.

I leave the issue open for 1) to be answered, but the rest is clear now. Thanks @cstritzke !

**Comment by cstritzke** [comment]
Concerning 1): Did you delete the gen/mininet folder and try starting it?

**Comment by ElisaRojas** [comment]
No, I didn't delete it. Anyway, my question is simpler, is it necessary to create or not? When I tried `vagrant up` I had created it and thus worked. But I did it because I remembered it from the old guide... since many things changed in the IDE, I don't know if that's a requisite anymore.

**Comment by cstritzke** [comment]
Looking at the code, I'm gonna say yes, you have to push the generate button before starting mininet.

**Comment by ElisaRojas** [comment]
Ok, perfect! Thanks!
