### ISSUE TITLE
"vagrant up" is not working currently (suggested solution inside)

### ISSUE THREAD

**Issue by ElisaRojas** [fp7-netide/IDE#26]
Hi @cstritzke ,

I tried `vagrant up` a couple of times and I always got this error:
![vagrant-up2](https://cloud.githubusercontent.com/assets/2779496/18162709/d3e9a814-7037-11e6-8ce0-8c5f8ed821f7.png)

The problem is that the link http://ftp.fau.de/apache/karaf/3.0.7/apache-karaf-3.0.7.tar.gz in the installation script is not working (404 response). I'd suggest to use the official one from the Apache repositories, which is: http://archive.apache.org/dist/karaf/3.0.7/apache-karaf-3.0.7.tar.gz
I changed it locally in my script and it worked. I haven't changed it in the master branch, just in case you want to check before. Please let me know if it's ok and I can add it myself or you, as you want.

By the way, is there any reason to use Karaf 3.0.7? I was using 3.0.5 and 3.0.6, but not 3.0.7. And the last version is 3.0.8. So I was just curious if there is some reason :)

Also, the ODL repo takes a looooooooong time to download. For some reason, the current link is not working very well, but the others with stable releases are working way better. This is not a problem itself, but maybe the provisioning would be shorter if we change the repo link we are using as well. (In any case, I'd not change this as we'll be moving soon to a new ODL release).

Thanks!

**Comment by cstritzke** [comment]
Hi Elisa,

I'm currently testing a new version of the installation scripts with apache 3.0.8. I also took the opportunity and changed the karaf directory in the vm from $HOME/apache-karaf-3._._ to $HOME/netide/core-karaf.

If the installation works, I'll push the new code to the master branch.

I didn't use the older karaf versions, simply because I couldn't find them :). Hence, I always try to use the newest one.

Concerning ODL: Good idea to change the repo. Do you have a better link?

Best
Christian

**Comment by cstritzke** [comment]
0100a6f5e418c242e28b043ea0400da89c9f5bd9 and ed074f3e2e6fe8394d4f2580cd12ca1232c47540 should fix the first problem.

**Comment by ElisaRojas** [comment]
Thank you Christian.

Concerning older Karaf versions, they are all in http://archive.apache.org/dist/karaf/ :)
About ODL, it has improved in the last days and now it only takes 30 minutes, which is reasonable. In any case, other repos are here: https://nexus.opendaylight.org/content/groups/public/org/opendaylight/integration/distribution-karaf/ But now that is working fine, maybe we can leave it as it is... :wink:
