### ISSUE TITLE
Error after master/ssh_config_extension branchs update

### ISSUE THREAD

**Issue by ElisaRojas** [fp7-netide/IDE#29]
Hi @cstritzke ,

I've updated the master branch and now I get the following errors:

![ide-master](https://cloud.githubusercontent.com/assets/2779496/18907391/c2a4e746-856b-11e6-830b-f68e1aacd2c2.png)

Then I've tried the ssh_config_extension branch, just in case this was something strictly related with the master branch and because I just wanted to test the new SSH options, but it still has the same amount of errors.

Any clues on how to solve it?

Thank you!

**Comment by cstritzke** [comment]
Have you tried regenerating the xtext source files for the respective projects? See https://github.com/fp7-netide/IDE/blob/master/README.md#compiler-errors-after-pulling

**Comment by ElisaRojas** [comment]
Thank @cstritzke , that was it! :+1:
