### ISSUE TITLE
Can't generate mininet confuguration

### ISSUE THREAD

**Issue by KevinPhemius** [fp7-netide/IDE#3]
Hello,

I'm following the tutorial to implement UC3.
I used to be able to generate a mininet file in the previous version, now I can't (the option doesn't show up).

Best,

Kévin

**Comment by KevinPhemius** [comment]
IDK if relevant but when I start the eclipse application (the second one, for modelling) the first one has a buch of error in the console : 

!SESSION 2015-06-02 11:39:17.390 -----------------------------------------------
eclipse.buildId=4.4.0.I20140606-1215
java.version=1.7.0_65
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.platform.ide
Command-line arguments:  -product org.eclipse.platform.ide -data /home/tai/workspace/../runtime-EclipseApplication -dev file:/home/tai/workspace/.metadata/.plugins/org.eclipse.pde.core/Eclipse Application/dev.properties -os linux -ws gtk -arch x86 -consoleLog

!ENTRY eu.netide.configuration.launcher 4 0 2015-06-02 11:39:19.758
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: eu.netide.configuration.launcher [750]
  Unresolved requirement: Require-Bundle: org.eclipse.debug.ui; bundle-version="3.10.1"

```
at org.eclipse.osgi.container.Module.start(Module.java:434)
at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
```

!ENTRY eu.netide.configuration.utils 4 0 2015-06-02 11:39:19.763
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: eu.netide.configuration.utils [753]
  Unresolved requirement: Require-Bundle: org.eclipse.core.resources; bundle-version="3.9.1"

```
at org.eclipse.osgi.container.Module.start(Module.java:434)
at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
```

Loading ECPProjectManagerImpl from /home/tai/runtime-EclipseApplication/.metadata/.plugins/org.eclipse.emf.ecp.core/projects
ProviderDescriptor: org.eclipse.emf.ecp.cdo.core [945] --> file:/home/tai/eclipse-modeling/plugins/org.eclipse.emf.ecp.cdo.core_1.3.0.20140610-1606.jar
ProviderDescriptor: org.eclipse.emf.ecp.emfstore.core [953] --> file:/home/tai/eclipse-modeling/plugins/org.eclipse.emf.ecp.emfstore.core_1.3.0.20140610-1606.jar
ProviderDescriptor: org.eclipse.emf.ecp.workspace.core [1023] --> file:/home/tai/eclipse-modeling/plugins/org.eclipse.emf.ecp.workspace.core_1.3.0.20140610-1606.jar

**Comment by cstritzke** [comment]
Hi,

did you select the Network Environment element in the model after double-clicking the .topology file and expanding the model tree?

Also, are you using [Eclipse Modeling Edition Luna SR2](http://www.eclipse.org/downloads/packages/eclipse-modeling-tools/lunasr2)?

Best
Christian

**Comment by KevinPhemius** [comment]
Hi,

I did select the Network Environment. There is no "mininet" option when I right click.
I use Eclipse Modeling Tools Version: Luna Release (4.4.0) Build id: 20140612-0600

**Comment by KevinPhemius** [comment]
I try to use "validate", here is the error (same for each host) : 

Unable to find delegate to evaluate the 'nodirectconnection' constraint on 'Host h1': http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot   UC3.topology    /UC3    Unknown EMF Problem

**Comment by cstritzke** [comment]
I'm using [Luna SR2 (4.4.2) Build id: M20150204-1700](http://www.eclipse.org/downloads/packages/eclipse-modeling-tools/lunasr2). Could you try that one? It should be the current version on the website.
Also, switching to the development branch can help.
I haven't seen your error yet. If switching to the newer version doesn't fix the problem, I'll try to reproduce it.

**Comment by antonis-m** [comment]
I have pretty much the same issue as Kevin. I am using the eclipse version mentioned above (SR2 4.4.2) and I am trying to build a simple network topology. Any help would be much appreciated :)

**Comment by cstritzke** [comment]
Strange... and the plugin "eu.netide.generator" is in your workspace (of the first eclipse instance)?

Can you run your apps, i.e. set up a run configuration, choose a topology and apps and launch it?

**Comment by KevinPhemius** [comment]
I can't seem to.
I don't see the same things as in the demo.

**Comment by antonis-m** [comment]
Correction: No I cannot run the app, I cannot see the NetIDE controller deployment in the panel..

**Comment by farhaven** [comment]
> I used to be able to generate a mininet file in the previous version

Did you update the plugins in-place? If not, are you sure you've imported them correctly?

**Comment by KevinPhemius** [comment]
I deleted everything and re-cloned the repo.
I then followed the usual steps (in the tutorial).

**Comment by cstritzke** [comment]
I just talked to Antonis and we found out that it was unclear that all the projects from the plugin folder have to be in the workspace root. So in the end you should have the following structure in your workspace root:

```
  eu.netide.configuration.launcher  
  eu.netide.configuration.generator
  eu.netide.configuration.preferences
  eu.netide.configuration.utils
  eu.netide.configuration
  eu.netide.configuration.edit
  eu.netide.configuration.editor
  eu.netide.configuration.tests
```

I updated the readme in the master and development branch accordingly
