### ISSUE TITLE
Status of the core integration

### ISSUE THREAD

**Issue by cstritzke** [fp7-netide/IDE#9]
Hi,

I just tested the core integration. After a small fix in the installation script and the startup commands, I got Karaf and the Core prompt working.
What's still missing is a sample composition.xml file (or a stub) in the Composition folder.
I have a fix for that ready and I can push it if you agree.

I'm not sure how we specify and start the shim and the backend controllers. Tim, is there any documentation on how to use the core CLI correctly?

Best
Christian

**Comment by TimVinkemeier** [comment]
For now, we have only this ("How to deploy" section). When I handed in my master's thesis, you will have more :D

**Comment by TimVinkemeier** [comment]
https://github.com/fp7-netide/Engine/blob/CoreImplementation/core/Readme.md

**Comment by ElisaRojas** [comment]
Hi Christian, 

I think @andres-beato has already tried some example. In any case, I think we just need the file used by @sergiotamu in the tests.

**Comment by andres-beato** [comment]
Hi Christian,

Yes, push your code please.

Regarding the composition file, I think we need the file used by
@sergiotamu for the test.

Hi Christian,

I think @andres-beato https://github.com/andres-beato has already tried
some example. In any case, I think we just need the file used by @sergiotamu
https://github.com/sergiotamu in the tests.

**Comment by sergiotamu** [comment]
Hello all, 

Here you are the Composition Specification file which I am using for testing purposes.
![seleccion_005](https://cloud.githubusercontent.com/assets/9716567/10461150/480d68fc-71d8-11e5-9c2b-f236c82119ce.png)

I attach an image due to xml files are not supported.

**Comment by cstritzke** [comment]
Thanks a lot! The code is in the repo. Whenever a new project is created, the sample composition file is created as well.

**Comment by ElisaRojas** [comment]
Hi @cstritzke , do you have any other problem deploying the core? should we close this issue now? :smile:

**Comment by cstritzke** [comment]
Oh, right. Let's close it :)
